version: '3'

services:
  db:
    image: postgres:latest
    restart: always
    ports:
      - '5432:5432'
    environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
        - POSTGRES_DB=cloud_storage
  cache:
    image: redis:6.0
    ports:
      - '16379:6379'
    environment:
      - REDIS_PASSWORD=redispass
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
  backend:
    build:
      context: .
    ports:
      - '8888:8888'
    environment:
      spring_datasource_url: jdbc:postgresql://db:5432/cloud_storage
      spring_datasource_username: postgres
      spring_datasource_password: postgres

      spring_redis_password: redispass
      spring_redis_host: cache
      spring_redis_port: 6379
    depends_on:
      - db
      - cache